### ISSUE TITLE
Volumetric light beams using shaders

### ISSUE THREAD

**Issue by ravitejaaketi** [kosua20/Technique-iOS#1]
Is it possible to create volumetric light beams using shaders? Can you provide any tutorials
Thanks

**Comment by kosua20** [comment]
Hello,
light shafts or god rays can be done using shaders, in multiple ways.

The first option is kind of a "trick". The idea is to render light sources in a framebuffer, apply a radial blur and compose this with the rendered scene. See for instance http://zompi.pl/light-shafts-b/, https://github.com/Erkaman/glsl-godrays, https://developer.nvidia.com/gpugems/GPUGems3/gpugems3_ch13.html, http://fabiensanglard.net/lightScattering/

Alternatively you can pick a more "bruteforce" approach, where you raymarch through the volume where you want to have such effects, and check what fraction of points along the ray are receiving light. See http://www.alexandre-pestana.com/volumetric-lights/ for instance

Both options will require multiple passes and shaders.

**Comment by ravitejaaketi** [comment]
Hello,

I want to apply light rays/glow to SCENE KIT NODE in IOS ARKIT

I am newbie to metal/shaders

*Do you have any example code?*


Thanks & Regards
Raviteja Aketi

**Comment by kosua20** [comment]
Hello,
this is not provided by SceneKit, so you would have to implement it using either custom materials, shader modifiers or SCNTechnique. This would mean taking inspiration from what is done in openGL or Unity and try to "translate" it to SceneKit. I haven't seen any example code for this, though.
